# Generated by Django 5.1 on 2024-11-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_goal_created_at_goal_description_goal_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
