# Generated by Django 5.1 on 2024-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_goal_created_at_goal_description_goal_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayentry',
            options={'ordering': ['-date'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
